### ISSUE TITLE
1.9.1 - Window focus, and shortcut

### ISSUE THREAD

**Issue by AgamlaRage** [zaggino/brackets-electron#86]
Brackets-Electron 1.9.1
Windows 10

I use to open normal brackets in one screen and electron in an other (so I can see diferents project ...etc).
Since the Electron 1.9.1 update, when I do that, brackets-electron do weird things when I change the window focus.

Examples: 
- In normal brackets, shortcut  (like Ctrl+A, Ctrl+Z, ...etc) won't work
- In windows, shortcut (like Ctrl+N) won't work)
( in normal case, in Windows when you have a open "folder window" that is focus, the shortcut Ctrl+N will open a new "folder window" in the same directory).

**Comment by ghost** [comment]
Maybe this is related. I've found Brackets-electron 1.9.1 *steals* all keyboard shortcuts, even though Other program is focused. Tested with Firefox, Notepad++ and other programs.

Win7/Brackets-electron 1.9.1

**Comment by AgamlaRage** [comment]
@mskocik you are right, and this is a good description of the issue.

**Comment by zaggino** [comment]
This is a fuck-up indeed. Will release 1.9.2 shortly, sorry guys.

**Comment by zaggino** [comment]
https://github.com/zaggino/brackets-electron/releases/tag/v1.9.2

**Comment by r4p7or** [comment]
OS: Windows 7 64bit
Brackets-Electron Release 1.9 build 1.9.3

**It still usurps those shortcuts.**

For example:
- Brackets-Electron is minimized. 
- I'm  working in other programs and copying and pasting a text using Ctrl+C and Ctrl+V (from OneNote to Directory Opus adress bar)  when suddenly Ctrl+V stops working. Nothing gets pasted. I have to use right-click menu > Paste.
- Then I click on the Brackets-El in the taskbar (which was minimized and out of focus the whole time) and the pasted text is there.


_I wanted to post this as a new issue but I came across this thread (although closed). I hope it's OK._

**Comment by zaggino** [comment]
@r4p7or please test with https://github.com/zaggino/brackets-electron/releases/tag/v1.9.4

**Comment by r4p7or** [comment]
Hi, unfortunately even 1.9.4 still steals shortcuts.

It doesnt steal them all the time - I reckon in 1 case out of 30 (just a rough estimate).

Since this morning I've left Brackets-El minimized  and carried on working on my projects waiting for the issue to appear or not.


It has stolen 2 "shortcuts" so far:

1st was Ctrl + B
- In OneNote I wanted to make a text selection bold using Ctrl + B
- nothing happened
- restored the minimized Brackets-El to find out that Ctrl + B was applied there (Add Next Match To Selection)

2nd was Ctrl + G
- In Adobe Illustrator I wanted to group several objects using Ctrl + G
- nothing happened
- restored the minimized Brackets-El to find out that Ctrl + G was applied there (Go To Line)

**Comment by zaggino** [comment]
@r4p7or ok, the fix is a hack right now and I'd need to report a bug with electron to fix this. Basically, when I remove the hack, the ctrl+d (notice the case) doesn't work but ctrl+D (capslock enabled) does ... this was reported as https://github.com/zaggino/brackets-electron/issues/79

For now, if I remove hack, it will make some shortcuts to stop working. If I leave it, it will sometime steal shortcuts of other apps, bad choices both.

**Comment by zaggino** [comment]
Should be fixed in https://github.com/zaggino/brackets-electron/releases/tag/v1.10.2 completely.
